export const siteMapData = [
  {
    path: 'docs/toto',
    dirPath: 'docs/toto',
    name: 'toto',
    slug: '/toto/',
    level: 1,
    title: '',
    order: null,
    description: null,
    type: 'directory',
    content: [],
    isOpened: false,
    isPartOfCurrentlocation: false,
  },
  {
    path: 'docs/example',
    dirPath: 'docs/example',
    name: 'example',
    slug: '/example/',
    level: 1,
    title: 'Getting started',
    order: 3,
    description:
      'Here are the Components! There are a lot of them and they are very cool and well designed!',
    type: 'directory',
    content: [
      {
        path: 'docs/example/level2',
        dirPath: 'docs/example/level2',
        name: 'level2',
        slug: '/example/level2/',
        level: 2,
        title: '',
        order: null,
        description: null,
        type: 'directory',
        content: [],
        isOpened: false,
        isPartOfCurrentlocation: false,
      },
    ],
    isOpened: false,
    isPartOfCurrentlocation: false,
  },
];
